import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = inter({
  variable: "--inter",
  subsets: ["latin"],
});

const montserrat = montserrat({
  variable: "--montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {children}
      <body className={`${inter.variable} ${montserrat.variable} antialiased`}>
        <ThemeContextProvider>
          <Header />
          <main className=" min-h-screen">{children}</main>
          <Footer />
        </ThemeContextProvider>
      </body>
    </html>
  );
}
